apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vowpal-wabbit.fullname" . }}
  labels:
    app: {{ template "vowpal-wabbit.name" . }}
    chart: {{ template "vowpal-wabbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vowpal-wabbit.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vowpal-wabbit.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gitlab-docker-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{ toYaml .Values.image.args | indent 12 }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: vowpal
              containerPort: 26542
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              initialDelaySeconds: 5
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              initialDelaySeconds: 5
              periodSeconds: 5
          env:
          - name: VOWPAL_WABBIT_MODEL_NAME
            value: {{ .Release.Name }}
          envFrom:
          - secretRef:
              name: {{ template "vowpal-wabbit.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /app/saved-data
            {{- if .Values.persistence.subPath }}
            subPath: {{ .Values.persistence.subPath }}
            {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "vowpal-wabbit.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.podAffinity }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Values.podAffinity.matchLabelsApp }}
                  release: {{ .Release.Name }}
                  heritage: {{ .Release.Service }}
              topologyKey: kubernetes.io/hostname
            weight: 1
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
