apiVersion: v2
kind: Secret
metadata:
  name: {{ template "vowpal-wabbit.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.environment }}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}

