apiVersion: v1
kind: Service
metadata:
  name: {{ template "vowpal-wabbit.fullname" . }}
  labels:
    app: {{ template "vowpal-wabbit.name" . }}
    chart: {{ template "vowpal-wabbit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.porthttp }}
      targetPort: 5000
      protocol: TCP
      name: http
    - port: {{ .Values.service.portvowpal }}
      targetPort: 26542
      protocol: TCP
      name: vowpal
  selector:
    app: {{ template "vowpal-wabbit.name" . }}
    release: {{ .Release.Name }}
