apiVersion: v1
kind: Service
metadata:
  name: {{ template "sshd.fullname" . }}
  labels:
    app: {{ template "sshd.name" . }}
    chart: {{ template "sshd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "sshd.name" . }}
    release: {{ .Release.Name }}
