apiVersion: v1
kind: Service
metadata:
  name: {{ template "omnidb.fullname" . }}
  labels:
    app: {{ template "omnidb.name" . }}
    chart: {{ template "omnidb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.webSocketPort }}
      targetPort: 25482
      protocol: TCP
      name: http-websocket
  selector:
    app: {{ template "omnidb.name" . }}
    release: {{ .Release.Name }}
