apiVersion: v2
name: clair
home: https://coreos.com/clair
version: 0.2.2
appVersion: v2.1.4
dependencies:
  - name: postgresql
    version: "10.0.0"
    condition: postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"
description: Clair is an open source project for the static analysis of vulnerabilities in application containers._
icon: https://cloud.githubusercontent.com/assets/343539/21630811/c5081e5c-d202-11e6-92eb-919d5999c77a.png
sources:
  - https://github.com/coreos/clair
maintainers:
  - name: Wiremind
    email: dev@wiremind.io

