apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scrapoxy.fullname" . }}
  labels:
    app: {{ template "scrapoxy.name" . }}
    chart: {{ template "scrapoxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  config.json: |-
    {
      "commander": {
        "port": {{ .Values.config.commander.port | quote }},
        "password": {{ .Values.config.commander.password | quote }}
      },

      "proxy": {
        "auth": {
          "username": {{ .Values.config.proxy.auth.username | quote }},
          "password": {{ .Values.config.proxy.auth.password | quote }}
        },
        "port": {{ .Values.config.proxy.port }}
      },

      "instance": {
        "port": {{ .Values.config.instance.port }},
        "scaling": {
          "min": {{ .Values.config.instance.scaling.min }},
          "max": {{ .Values.config.instance.scaling.max }}
        }
      },

      "providers": [
        {{- range .Values.config.providers }}
        {{- toJson . }}
        {{- end }}
      ]
    }
