{{- if .Values.ingressUpload.enabled -}}
{{- $fullNameUpload := printf "%s-upload" (include "pypi.fullname" .) -}}
{{- $fullName := include "pypi.fullname" . -}}
{{- $ingressPath := .Values.ingressUpload.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullNameUpload }}
  labels:
    app: {{ template "pypi.name" . }}
    chart: {{ template "pypi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingressUpload.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingressUpload.tls }}
  tls:
  {{- range .Values.ingressUpload.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingressUpload.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
