apiVersion: "v1"
appVersion: "2.9.0"
description: "OmniDB: Web tool for database management."
name: "omnidb"
version: "0.1.0"
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
