apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "clair.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "clair.matchLabels" $ | indent 6 }}
  template:
    metadata:
      labels:
{{ include "clair.labels" $ | indent 8 }}
    spec:
      volumes:
      - name: "{{ .Chart.Name }}-config"
        configMap:
          name: {{ template "fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "-log-level={{ .Values.logLevel }}"
        {{ if .Values.insecureTls }}- "--insecure-tls" {{end}}
        ports:
        - name: clair-api
          containerPort: {{ .Values.service.internalApiPort }}
          protocol: TCP
        - name: clair-health
          containerPort: {{ .Values.service.internalHealthPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalHealthPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalHealthPort }}
        volumeMounts:
        - name: "{{ .Chart.Name }}-config"
          mountPath: /etc/clair
        resources:
{{ toYaml .Values.resources | indent 10 }}
