apiVersion: v1
appVersion: "1.0"
description: pghoard
name: pghoard
version: 0.6.0
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
