apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pghoard.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "pghoard.name" . }}
data:
  PGHOARD_STORAGE_TYPE: "local"
  PGHOARD_BASEBACKUP_COUNT: "{{ .Values.basebackupCount }}"
  PGHOARD_BASEBACKUP_HOUR: "{{ .Values.baseBackupHour }}"
  PGHOARD_BASEBACKUP_INTERVAL_HOURS: "{{ .Values.basebackupIntervalHours }}"
  PGHOARD_DIRECTORY: /var/lib/pghoard
  PGHOARD_ACTIVE_BACKUP_MODE: pg_receivexlog
  # docker-pghoard creates a "site" (i.e backup) named $HOSTNAME, so we hijack it so that site name is stable
  HOSTNAME: {{ template "pghoard.fullname" . }}
