# XXX Not maintained, see wiremind/template/pghoard_secret.yaml
{{- if not .Values.customSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pghoard.fullname" . }}
  labels:
    app: {{ template "pghoard.name" . }}
    chart: {{ template "pghoard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PG_HOST: {{ .Values.postgresql.host | b64enc }}
  PG_PORT: "{{ .Values.postgresql.port | b64enc }}"
  PG_USER: {{ .Values.postgresql.user | b64enc }}
  PG_PASSWORD: "{{ .Values.postgresql.password | b64enc }}"
{{- end }}

