apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes_
name: sshd
version: 0.1.1
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
